# Application Configuration
app:
  name: "ATMT Service"
  version: "1.0.0"
  environment: "development" # development, staging, production
  debug: true

# Server Configuration
server:
  host: "localhost"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  graceful_shutdown_timeout: 30s

# Database Configuration
database:
  driver: "mongodb" # mongodb, postgres, mysql, sqlite
  uri: "mongodb://root:passw0rd@100.120.169.11/automationtool?authSource=admin"
  name: "automationtool"
  host: "100.120.169.11"
  port: 27017
  username: "root"
  password: "passw0rd"
  ssl_mode: "disable"
  max_pool_size: 25
  min_pool_size: 5
  connection_timeout: 30s

# Redis Configuration (for caching/sessions)
redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  pool_size: 10
  min_idle_connections: 5

# Logging Configuration
logging:
  level: "info" # debug, info, warn, error
  format: "json" # json, text
  output: "stdout" # stdout, file
  file_path: "logs/app.log"
  max_size: 100 # MB
  max_backups: 3
  max_age: 28 # days

# CORS Configuration
cors:
  allowed_origins: 
    - "http://localhost:3000"
    - "http://localhost:8080"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Accept"
    - "Authorization"
    - "Content-Type"
    - "X-CSRF-Token"
  exposed_headers: []
  allow_credentials: true
  max_age: 86400

# JWT Configuration
jwt:
  secret: "your-super-secret-jwt-key"
  expiration: 24h
  refresh_expiration: 168h # 7 days

# Rate Limiting
rate_limit:
  requests_per_minute: 60
  burst: 10

# External APIs
external_apis:
  timeout: 30s
  retry_attempts: 3
  retry_delay: 1s

# File Upload
file_upload:
  max_size: 10485760 # 10MB in bytes
  allowed_types:
    - "image/jpeg"
    - "image/png"
    - "image/gif"
    - "application/pdf"
  upload_path: "uploads/"

# Health Check
health_check:
  enabled: true
  endpoint: "/health"

# Metrics
metrics:
  enabled: true
  endpoint: "/metrics"
  namespace: "atmt"
