# Development Environment Configuration
app:
  name: "ATMT Service"
  version: "1.0.0"
  environment: "development"
  debug: true

server:
  host: "localhost"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  graceful_shutdown_timeout: 30s

database:
  driver: "mongodb"
  uri: "mongodb://root:passw0rd@100.120.169.11/automationtool"
  name: "automationtool"
  host: "100.120.169.11"
  port: 27017
  username: "root"
  password: "passw0rd"
  ssl_mode: "disable"
  max_pool_size: 10
  min_pool_size: 5
  connection_timeout: 30s

redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  pool_size: 10
  min_idle_connections: 5

logging:
  level: "debug"
  format: "text"
  output: "stdout"
  file_path: "logs/dev.log"
  max_size: 100
  max_backups: 3
  max_age: 28

cors:
  allowed_origins: 
    - "*"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "*"
  exposed_headers: []
  allow_credentials: true
  max_age: 86400

jwt:
  secret: "dev-jwt-secret-key"
  expiration: 24h
  refresh_expiration: 168h

rate_limit:
  requests_per_minute: 100
  burst: 20

external_apis:
  timeout: 30s
  retry_attempts: 3
  retry_delay: 1s

file_upload:
  max_size: 10485760
  allowed_types:
    - "image/jpeg"
    - "image/png"
    - "image/gif"
    - "application/pdf"
  upload_path: "uploads/"

health_check:
  enabled: true
  endpoint: "/health"

metrics:
  enabled: true
  endpoint: "/metrics"
  namespace: "atmt"
